//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO.NET_EntityFramework_03_HW.CreateDataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int intEquipmentId { get; set; }
        public string intGarageRoom { get; set; }
        public string strManufYear { get; set; }
        public Nullable<int> intSNPrefixId { get; set; }
        public int Manufacturer_intManufacturerID { get; set; }
        public int ModelModelId { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Model Model { get; set; }
    }
}
