//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO.NET_EntityFramework_03_HW.CreateDataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MCSContainer : DbContext
    {
        public MCSContainer()
            : base("name=MCSContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Model> ModelSet { get; set; }
        public virtual DbSet<Equipment> EquipmentSet { get; set; }
        public virtual DbSet<Manufacturer> ManufacturerSet { get; set; }
    }
}
